<?php

         //Array with all stock codes in India Nifty 50 for searching portfolio
  $Nifty50Stocks = array("LT","ACC","ADANIPORTS","AMBUJACEM","ASIANPAINT","AUROPHARMA","AXISBANK","BAJAJ-AUTO","BANKBARODA","BPCL","BHARTIARTL","BOSCHLTD","CIPLA","COALINDIA","DRREDDY","EICHERMOT","GAIL","GRASIM","HCLTECH","HDFCBANK","HEROMOTOCO","HINDALCO","HINDUNILVR","HDFC","INFRATEL","ITC", "IOC","ICICIBANK","IBULHSGFIN","INDUSINDBK","INFY","KOTAKBANK","LUPIN","M&M","MARUTI","NTPC","ONGC","POWERGRID","RELIANCE","SBIN","SUNPHARMA","TCS","TATAMOTORS","TATAMTRDVR","TATAPOWER","TATASTEEL","TECHM","ULTRATECH","WIPRO","YESBANK","ZEEL");
        
  $Nifty50StockNames = array( "LT"  => "Larsen & Toubro Ltd.",
                              "ACC" => "ACC Limited",
                              "ADANIPORTS" => "Adani Ports & SEZ Limited",
                              "AMBUJACEM" => "Ambuja Cements Ltd.",
                              "ASIANPAINTSS" => "Asian Paints Ltd.",
                              "AUROPHARMA" => "Aurobindo Pharma Ltd.",
                              "AXISBANK" => "Axis Bank Ltd.",
                              "BAJAJ-AUTO" => "Bajaj Auto Ltd.",
                              "BANKBARODA" => "Bank of Baroda",
                              "BPCL" => "Bharat Petroleum Corporation",
                              "BHARATIARTL" => "BhartiAirtel Ltd.",
                              "BOSCHLTD" => "Bosch Ltd.",
                              "CIPLA" => "Cipla Ltd.",
                              "COALINDIA" => "Coal India Ltd.",
                              "DRREDDY" => "Dr. Reddy's Laboratories Ltd.",
                              "EICHERMOT" => "Eicher Motors",
                              "GAIL" => "GAIL (India) Ltd.",
                              "GRASIM" => "Grasim Industries Ltd.",
                              "HCLTECH" => "HCL Technologies Ltd.",
                              "HDFCBANK" => "HDFC Bank Ltd.",
                              "HEROMOTOCO" => "Hero MotoCorp Ltd.",
                              "HINDALCO" => "Hindalco Industries Ltd.",
                              "HINDUNILVR" => "HindustanUnilever Ltd.",
                              "HDFC" => "Housing Development Finance Corporation Ltd.",
                              "INFRATEL" => "Bharti Infratel",
                              "ITC" => "ITC Limited",
                              "IOC" => "Indian Oil Corporation",
                              "ICICIBANK" => "ICICI Bank Ltd.",
                              "IBULHSGFIN" => "Indiabulls Housing Finance",
                              "INDUSINDBK" => "IndusInd Bank Ltd.",
                              "INFY" => "Infosys Ltd.",
                              "KOTAKBANK" => "Kotak Mahindra Bank Ltd.",
                              "LUPIN" => "Lupin Limited",
                              "M&M" => "Mahindra & Mahindra Ltd.",
                              "MARUTI" => "Maruti Suzuki India Ltd.",
                              "NTPC" => "NTPC Limited",
                              "ONGC" => "Oil & Natural Gas Corporation Ltd.",
                              "POWERGRID" => "PowerGrid Corporation of India Ltd.",
                              "RELIANCE" => "Reliance Industries Ltd.",
                              "SBIN" => "State Bank of India",
                              "SUNPHARMA" => "Sun Pharmaceutical Industries",
                              "TCS" => "Tata Consultancy Services Ltd.",
                              "TATAMOTORS" => "Tata Motors Ltd.",
                              "TATAMTRDVR" => "Tata Motors (DVR)",
                              "TATAPOWER" => "Tata Power Co. Ltd.",
                              "TATASTEEL" => "Tata Steel Ltd.",
                              "TECHM" => "Tech Mahindra Ltd.",
                              "ULTRATECH" => "UltraTech Cement Ltd.",
                              "WIPRO" => "Wipro",
                              "YESBANK" => "Yes Bank Ltd.",
                              "ZEEL" => "Zee Entertainment Enterprises Ltd."
                              );
        
        //Array with all stocks codes for DOW 30 for searching portfolio
        $DOW30Stocks = array("V","MMM","AXP","AAPL","BA","CAT","CVX",
                             "CSCO","KO","DIS","DD","XOM","GE","GS",
                             "HD","IBM","INTC","JNJ","JPM","MCD","MRK",
                             "MSFT","NKE","PFE","PG","TRV","UTX","UNH",
                             "VZ","WMT");
        
        $DOW30StockNames = array("V" => "Visa",
                                 "MMM" => "3M",
                                 "AXP" => "American Express",
                                 "AAPL" => "Apple",
                                 "BA" => "Boeing",
                                 "CAT" => "Caterpillar",
                                 "CVX" => "Chevron",
                                 "CSCO" => "Cisco",
                                 "KO" => "Coca-Cola",
                                 "DIS" => "Disney",
                                 "DD" => "E I du Pont de Nemours and Co",
                                 "XOM" => "Exxon Mobil",
                                 "GE" => "General Electric",
                                 "GS" => "Goldman Sachs",
                                 "HD" => "Home Depot",
                                 "IBM" => "IBM",
                                 "INTC" => "Intel",
                                 "JNJ" => "Johnson & Johnson",
                                 "JPM" => "JPMorgan Chase",
                                 "MCD" => "McDonald's",
                                 "MRK" => "Merck",
                                 "MSFT" => "Microsoft",
                                 "NKE" => "Nike",
                                 "PFE" => "Pfizer",
                                 "PG" => "Proctor & Gamble",
                                 "TRV" => "Travelers Companies Inc",
                                 "UTX" => "United Technologies",
                                 "UNH" => "United Health",
                                 "VZ" => "Verizon",
                                 "WMT" => "Walmart",
                                 );
?>